package meilisearch

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/hashicorp/vault/sdk/framework"
	"github.com/hashicorp/vault/sdk/logical"
)

const secretType = "meilisearch_key"

func secretMeilisearchKey(b *backend) *framework.Secret {
	return &framework.Secret{
		Type: secretType,
		Fields: map[string]*framework.FieldSchema{
			"key": {
				Type:        framework.TypeString,
				Description: "The Meilisearch API key.",
			},
			"uid": {
				Type:        framework.TypeString,
				Description: "The UID of the Meilisearch API key.",
			},
		},
		Revoke: b.secretKeyRevoke,
		Renew:  b.secretKeyRenew,
	}
}

func pathCreds(b *backend) []*framework.Path {
	return []*framework.Path{
		{
			Pattern: "creds/" + framework.GenericNameRegex("name"),
			DisplayAttrs: &framework.DisplayAttributes{
				OperationPrefix: "meilisearch",
				OperationVerb:   "request",
				OperationSuffix: "credentials",
			},
			Fields: map[string]*framework.FieldSchema{
				"name": {
					Type:        framework.TypeLowerCaseString,
					Description: "The name of the role to generate credentials for.",
					Required:    true,
				},
			},
			Operations: map[logical.Operation]framework.OperationHandler{
				logical.ReadOperation: &framework.PathOperation{
					Callback: b.pathCredsRead,
				},
			},
			HelpSynopsis:    "Generate a Meilisearch API key from a role.",
			HelpDescription: "This path generates a dynamic Meilisearch API key based on the named role.",
		},
	}
}

func (b *backend) pathCredsRead(ctx context.Context, req *logical.Request, data *framework.FieldData) (*logical.Response, error) {
	roleName := data.Get("name").(string)

	role, err := getRole(ctx, req.Storage, roleName)
	if err != nil {
		return nil, err
	}
	if role == nil {
		return logical.ErrorResponse("role %q not found", roleName), nil
	}

	client, err := b.getClient(ctx, req.Storage)
	if err != nil {
		return nil, err
	}

	// Calculate expiration based on TTL.
	ttl := role.TTL
	if ttl == 0 {
		ttl = b.System().DefaultLeaseTTL()
	}
	maxTTL := role.MaxTTL
	if maxTTL == 0 {
		maxTTL = b.System().MaxLeaseTTL()
	}
	if ttl > maxTTL {
		ttl = maxTTL
	}

	expiresAt := time.Now().UTC().Add(ttl)

	keyName := fmt.Sprintf("vault-%s-%d", roleName, time.Now().UnixNano())
	keyDesc := fmt.Sprintf("Dynamic key generated by Vault for role %q", roleName)

	keyResp, err := client.CreateKey(ctx, keyName, keyDesc, role.Actions, role.Indexes, &expiresAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create Meilisearch API key: %w", err)
	}

	resp := b.Secret(secretType).Response(map[string]interface{}{
		"key":         keyResp.Key,
		"uid":         keyResp.UID,
		"name":        keyResp.Name,
		"description": keyResp.Description,
		"actions":     keyResp.Actions,
		"indexes":     keyResp.Indexes,
		"expires_at":  keyResp.ExpiresAt.Format(time.RFC3339),
		"created_at":  keyResp.CreatedAt.Format(time.RFC3339),
	}, map[string]interface{}{
		"uid":  keyResp.UID,
		"role": roleName,
	})

	resp.Secret.TTL = ttl
	resp.Secret.MaxTTL = maxTTL

	return resp, nil
}

func (b *backend) secretKeyRevoke(ctx context.Context, req *logical.Request, _ *framework.FieldData) (*logical.Response, error) {
	uid, ok := req.Secret.InternalData["uid"].(string)
	if !ok || uid == "" {
		return nil, fmt.Errorf("uid is missing from secret internal data")
	}

	client, err := b.getClient(ctx, req.Storage)
	if err != nil {
		return nil, err
	}

	if err := client.DeleteKey(ctx, uid); err != nil {
		// If the key is already gone, that's fine.
		if strings.Contains(err.Error(), "api_key_not_found") {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to delete Meilisearch API key: %w", err)
	}

	return nil, nil
}

func (b *backend) secretKeyRenew(ctx context.Context, req *logical.Request, _ *framework.FieldData) (*logical.Response, error) {
	roleName, ok := req.Secret.InternalData["role"].(string)
	if !ok || roleName == "" {
		return nil, fmt.Errorf("role is missing from secret internal data")
	}

	role, err := getRole(ctx, req.Storage, roleName)
	if err != nil {
		return nil, err
	}
	if role == nil {
		return nil, fmt.Errorf("role %q no longer exists", roleName)
	}

	resp := &logical.Response{Secret: req.Secret}
	resp.Secret.TTL = role.TTL
	resp.Secret.MaxTTL = role.MaxTTL

	return resp, nil
}
